spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/clients
    username: postgres
    password: clients
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    show-sql: true